title: BoobooWei
subtitle: "A fast, simple & powerful blog framework powered by Node.js."
description: "Hexo is a fast, simple & powerful blog framework powered by Node.js."
author: 魏亚萍
language: zh-cn
timezone: UTC

url: http://www.toberoot.com
root: /
permalink: news/:year/:month/:day/:title/
archive_dir: news
code_dir: downloads/code
new_post_name: :year-:month-:day-:title.md # File name of new posts
post_asset_folder: true
per_page: 0
pretty_urls:
  trailing_index: false
  trailing_html: false

theme: navy

highlight:
  enable: true
  line_number: false

disqus_shortname: toberoot
google_analytics: UA-48498357-3
fb_admins: 100000247608790
algolia:
  zh-cn:
    api_key: ad652bf20bcd81434ad119c8cf34722e
    index_name: toberoot
github: BoobooWei

#deploy:
#  - type: git
#    repository: git@github.com:BoobooWei/booboowei.github.io.git
#    branch: master
