<footer id="footer" class="wrapper">
  <div class="inner">
    <div id="footer-copyright">
      &copy; {{ moment(Date.now()).year() }} <a href="https://github.com/hexojs/hexo/graphs/contributors" target="_blank">{{ config.author }}</a><br>
      Documentation licensed under <a href="https://choosealicense.com/licenses/agpl-3.0/" target="_blank">GNU AGPLv3</a><br>
      备案号：沪ICP备2020026043号
    </div>
    <div id="footer-links">
      <a href="https://github.com/{{ config.github }}" class="footer-link" target="_blank"><i class="fa fa-github-alt"></i></a>
      <a href="http://exam.toberoot.com/">在线测评系统</a><
      <a href="https://www.huangjingxue.com/" target="_blank">衾袭</a><
      <a href="https://husky-wu.github.io/" target="_blank">明夋</a><
      <a href="https://footman-ljn.github.io/" target="_blank">伊斯</a>
    </div>
  </div>
  <br>
  <div class="inner">
  </div>
</footer>
